### ISSUE TITLE
Relevant Repository

### ISSUE THREAD

**Issue by g3rley** [naomilago/similarity_search#1]
I found the repository very interesting. It's been really great to follow your professional development in these skills and competencies!

Thankful for having networks like this!

**Comment by naomilago** [comment]
Thanks. I've written an article about Information Retrieval and Vector Search on LinkedIn, if you have interest in these topics you might like :)

https://www.linkedin.com/pulse/recupera%C3%A7%C3%A3o-de-informa%C3%A7%C3%A3o-com-pesquisa-vetorial-naomi-lago-
